version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: rd-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rd-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal
      - public

  migrate:
    image: ${ECR_IMAGE}
    command: ["npm", "run", "db:migrate:prod"]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal

  seed:
    image: ${ECR_IMAGE}
    command: [ "npm", "run", "db:seed:prod" ]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - internal

  api:
    image: ${ECR_IMAGE}
    container_name: rd-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      seed:
        condition: service_completed_successfully
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      PORT: 3000

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}

      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_CLOUDFRONT_URL: ${AWS_CLOUDFRONT_URL}

      FILES_PRESIGN_EXPIRES_IN_SEC: ${FILES_PRESIGN_EXPIRES_IN_SEC}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_PREFETCH: ${RABBITMQ_PREFETCH}
      PAYMENTS_GRPC_URL: ${PAYMENTS_GRPC_URL}
      PAYMENTS_GRPC_BIND_URL: ${PAYMENTS_GRPC_BIND_URL}
      PAYMENTS_RPC_TIMEOUT_MS: ${PAYMENTS_RPC_TIMEOUT_MS}
      PAYMENTS_RPC_MAX_RETRIES: ${PAYMENTS_RPC_MAX_RETRIES}
      PAYMENTS_RPC_BACKOFF_MS: ${PAYMENTS_RPC_BACKOFF_MS}

    ports:
      - "3000:3000"
    networks:
      - internal
      - public

volumes:
  db-data:

networks:
  internal:
    internal: true
  public: